/**
 * The published study areas, and how to address their data.
 *
 * `public/data/regions.json` is generated by the pipeline's run_region.R — it
 * is the list of regions that actually have files on disk, not the list that
 * exists in the pipeline's config. Nothing in the app hardcodes a region: the
 * route is dynamic, the switcher is rendered from this manifest, and the map
 * frames itself from each region's own bbox. Adding Osaka is a pipeline run,
 * not a frontend change.
 */

export interface Region {
  /** URL segment, e.g. "yokohama". The region name lowercased by the pipeline. */
  slug: string;
  /** Display name in English, and the pipeline's own key for the region. */
  name: string;
  /** Display name in Japanese. Optional in the config, so optional here. */
  label_ja?: string;
  /** The wards merged into this region, in config order. */
  wards: string[];
  /** [minLon, minLat, maxLon, maxLat] of the published hex grid. */
  bbox: [number, number, number, number];
}

export interface RegionManifest {
  /** Slug the bare "/" redirects to. */
  default: string;
  regions: Region[];
}

/**
 * Where a region's data files live.
 *
 * Every fetch in the app goes through this. Before it, each call site wrote
 * "/data/segments.geojson" as a literal and there was exactly one region's
 * worth of files behind that path — publishing a second region overwrote the
 * first rather than joining it.
 */
export function regionData(slug: string, file: string): string {
  return `/data/${slug}/${file}`;
}

/** The name to show, given the active locale. */
export function regionLabel(region: Region, locale: string): string {
  return locale === "ja" ? region.label_ja ?? region.name : region.name;
}

/**
 * MapLibre's bounds order, which is not the manifest's.
 *
 * The pipeline writes GeoJSON/sf order — [minLon, minLat, maxLon, maxLat] —
 * and MapLibre wants [[west, south], [east, north]].
 */
export function boundsOf(
  region: Region
): [[number, number], [number, number]] {
  const [w, s, e, n] = region.bbox;
  return [
    [w, s],
    [e, n],
  ];
}

/** Web Mercator northing, normalised to 0..1 over the whole world. */
function mercatorY(lat: number): number {
  const clamped = Math.max(-85.05, Math.min(85.05, lat));
  const rad = (clamped * Math.PI) / 180;
  return 0.5 - Math.log(Math.tan(Math.PI / 4 + rad / 2)) / (2 * Math.PI);
}

/**
 * A zoom floor that means "about the whole study area", whatever its size.
 *
 * The map used to hardcode minZoom 11, reasoned from Yokohama being ~12km
 * across — below it the region was a blob rather than a map. That reasoning is
 * sound and the number is not transferable: a single ward hits the same blob
 * two levels higher, and a prefecture-sized region would be clipped at 11.
 * Deriving it keeps the intent and drops the constant.
 *
 * The nominal viewport is deliberately generous, so the floor errs toward
 * letting the reader zoom out slightly past the region rather than fencing
 * them in at its exact edge.
 */
export function minZoomFor(
  region: Region,
  viewport: { width: number; height: number } = { width: 800, height: 700 }
): number {
  const [w, s, e, n] = region.bbox;
  const TILE = 256;

  const lonFraction = Math.abs(e - w) / 360;
  const latFraction = Math.abs(mercatorY(s) - mercatorY(n));

  const fit = (px: number, fraction: number) =>
    fraction > 0 ? Math.log2(px / (TILE * fraction)) : Infinity;

  const whole = Math.min(
    fit(viewport.width, lonFraction),
    fit(viewport.height, latFraction)
  );

  // One level of headroom below "just fits", then clamped: the lower bound
  // keeps a tiny study area from allowing a whole-globe view, the upper stops
  // a huge one from locking the reader in close.
  return Math.max(3, Math.min(14, Math.floor(whole) - 1));
}
